### ISSUE TITLE
Cannot grab on discordPTB

### ISSUE THREAD

**Issue by MashedTuna** [Rdimo/Hazard-Token-Grabber#4]
Traceback (most recent call last):
  File "NitroGenerator+Checker.py", line 253, in <module>
  File "NitroGenerator+Checker.py", line 133, in main
  File "NitroGenerator+Checker.py", line 77, in gettokens
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Dell\\AppData\\Roaming\\Discord\\Local Storage\\leveldb'

**Comment by Khaos11010** [comment]
its a virus i think i mean i saw someone upload it on a diff platform and it was a virus idk

**Comment by Khaos11010** [comment]
just use the v2 of the token logger

**Comment by Rdimo** [comment]
yes use v2 ty @Khaos11010
